version: '3'

services:
  db:
    image: mariadb:10.4
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3030:80
    environment:
      - PMA_ARBITRARY=1    
  
volumes:
  mariadb-data: